### ISSUE TITLE
Integrate offi-like french wondercards to roms

### ISSUE THREAD

**Issue by ghost** [Goppier/Gen3DistributionRoms#2]
Hello,

Would it be possible to integrate offi-like french wondercards to the roms you've made ?

You can get save files that contain the wondercard from my pack that is shared there : https://digiex.net/threads/french-megapack-1g-to-5g-pokemon-distribution-pack.16381/

Thank you

**Comment by Goppier** [comment]
We're currently working on translating all our events to all languages available! This will come out later this year
