### ISSUE TITLE
screen is white

### ISSUE THREAD

**Issue by GreenForzeGaming** [Goppier/Gen3DistributionRoms#5]
nothing seem too happen and the screen is just white after the code is launched on the gba

**Comment by GreenForzeGaming** [comment]
id love too shiny hunt for these pokemon, and as a streamer i would credit all work made here. i would love for this too work so bad XD

**Comment by ainsleyrutterford** [comment]
I had a similar issue and it turned out I had forgotten to patch the ROMs after I downloaded them. If you have the SuperCard SD GBA for example, you can follow [this YouTube video](https://www.youtube.com/watch?v=nzzFrSbHfaU&t=1237s).

**Comment by GreenForzeGaming** [comment]
this worked thankyou!
